### ISSUE TITLE
Combine all components into one website

### ISSUE THREAD

**Issue by NevilleMthw** [NevilleMthw/Option-Clutch#3]
I have different HTML pages which need to be combined as one website with accessing different sections through the navigation bar.

Do let me know if the issue needs to be clarified further.

**Comment by Aman0307** [comment]
@NevilleMthw I would like to contribute to this issue.

**Comment by NevilleMthw** [comment]
> @NevilleMthw I would like to contribute to this issue.

Do reference this issue in your PR. Thanks!

**Comment by Aman0307** [comment]
@NevilleMthw I have created a PR which solves issue #3. Please merge.

**Comment by NevilleMthw** [comment]
Thank you for your contribution!
